# Exceptions
# Neste caso temos que catar esta exceção envolvendo todo o bloco de código que pode gerar a exceção em um bloco try e tratar a exceção em um bloco except
while True:
  try:
    valor = int(input('Digite o valor em dolar: '))
    valor * 5.5
    break
  except ValueError:
    print('Digite apenas números inteiros')


















































































